version: "3.7"
services:
  mysql820:
    image: "mysql:8.2.0"
    ports:
      - "13306:3306"
    command: "--default-authentication-plugin=caching_sha2_password"
    environment:
      MYSQL_ROOT_PASSWORD: "root1234"
      MYSQL_DATABASE: "bluebell"
      MYSQL_PASSWORD: "root1234"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  redis507:
    image: "redis:5.0.7"
    ports:
      - "26379:6379"
  bluebell_app:
    build: .
    command: sh -c "./wait-for.sh mysql820:3306 redis507:6379 -- ./bluebell_app ./conf/config.yaml"
    depends_on:
      - mysql820
      - redis507
    ports:
      - "8888:8080"

