name: "web_app"
version: "v 0.0.1"
mode: "dev"
port: 8080

log:
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 5
  level: "debug"

mysql:
  host: "127.0.0.1"
  port: 3307
  user: "root"
  password: "youngking98"
  dbname: "sql_demo"
  max_open_coons: 200
  max_idle_coons: 10

redis:
  host: "127.0.0.1"
  port: 6379
  password: "youngking98"
  db: 0
  pool_size: 100