name: bluebell
version: "v 0.0.1"
mode: "dev"
machineID: 1
startTime: "2026-03-21"
port: ":8080"

log:
  fileName: "bluebell.log"
  level: "debug"
  maxAge: 30
  maxBackups: 5
  maxSize: 20

mysql:
  host: "127.0.0.1"
  port: 3307
  user: "root"
  password: "youngking98"
  dbname: "bluebell"
  maxOpenCoons: 200
  maxIdleCoons: 10

redis:
  host: "127.0.0.1"
  port: 6379
  password: "youngking98"
  db: 0
  poolSize: 20
  maxIdleCoons: 10
